defmodule Dayoff.Calendar.Tables do
  @moduledoc """
  The calendars that ship as lookup tables generated by `mix dayoff.sync`:
  Hijri and Hebrew (from the reference parser's own tables), the Chinese,
  Korean and Vietnamese lunisolar calendars with their solar terms, and the
  equinox and solstice dates. Each file is decoded once into
  `:persistent_term`.

  Outside a table's range a lookup returns no dates and logs a warning once,
  where the reference implementation stays silent.
  """

  require Logger

  alias Dayoff.Data

  @type mapped :: :hijri | :hebrew
  @type lunisolar :: :chinese | :korean | :vietnamese

  @doc """
  The dates of `day` of `month` in a mapped calendar that fall in the
  Gregorian `year`, the way the reference `CalEventMap.inYear` finds them:
  scanning the month's first days in the neighbouring Gregorian years,
  keeping the ones that land in `year`, and only the given calendar year
  when one is asked for. A month can start twice in one Gregorian year.

      iex> Dayoff.Calendar.Tables.mapped_dates(:hijri, 2026, 10, 1, nil)
      [~D[2026-03-20]]

      iex> Dayoff.Calendar.Tables.mapped_dates(:hebrew, 2026, 13, 14, nil)
      [~D[2026-03-03]]
  """
  @spec mapped_dates(mapped(), integer(), pos_integer(), integer(), integer() | nil) :: [Date.t()]
  def mapped_dates(calendar, year, month, day, calendar_year) do
    table = table(calendar)
    years = table["years"]

    if in_range?(calendar, years, year) do
      for y <- (year - 1)..(year + 1),
          first_days = years[Integer.to_string(y)] |> Enum.at(month - 1),
          first_days != nil,
          [gregorian_month, first_day, year_offset] <- Enum.chunk_every(first_days, 3),
          calendar_year == nil or calendar_year == table["base_year"] + year_offset,
          date = Date.add(Date.new!(y, gregorian_month + 1, first_day), day - 1),
          date.year == year,
          do: date
    else
      []
    end
  end

  defp in_range?(calendar, years, year) do
    if Enum.all?((year - 1)..(year + 1), &Map.has_key?(years, Integer.to_string(&1))) do
      true
    else
      warn_once(calendar, year)
      false
    end
  end

  @doc """
  The Gregorian date of a lunar date in the lunar year that starts in the
  Gregorian `year`, as the reference `date-chinese` computes it: a leap month
  request takes the month after the regular one, and `day` may run past the
  month (day 0 is the eve of the month). The table also carries the days
  where the reference's own round trip through its lunar labeling lands a
  day off from "day 1 plus the offset" (a handful per year, 2033 among
  them), so those match too.

      iex> Dayoff.Calendar.Tables.lunar_date(:chinese, 2026, 1, false, 1)
      ~D[2026-02-17]

      iex> Dayoff.Calendar.Tables.lunar_date(:chinese, 2026, 1, false, 0)
      ~D[2026-02-16]
  """
  @spec lunar_date(lunisolar(), integer(), 1..12, boolean(), integer()) :: Date.t() | nil
  def lunar_date(calendar, year, month, leap?, day) do
    case lunisolar_year(calendar, year) do
      nil -> nil
      entry -> lunar_month_date(entry, month, leap?, day)
    end
  end

  defp lunar_month_date(entry, month, leap?, day) do
    exception = if leap?, do: nil, else: entry["exceptions"]["#{month}-#{day}"]
    lunar_month_date(entry, month, leap?, day, exception)
  end

  defp lunar_month_date(_entry, _month, _leap?, _day, [gregorian_month, exact_day, gregorian_year]) do
    Date.new!(gregorian_year, gregorian_month, exact_day)
  end

  defp lunar_month_date(entry, month, leap?, day, nil) do
    [gregorian_month, first_day, gregorian_year] =
      Enum.at(entry[if(leap?, do: "leap_months", else: "months")], month - 1)

    Date.add(Date.new!(gregorian_year, gregorian_month, first_day), day - 1)
  end

  @doc """
  The Gregorian date of `day` of solar term `term` (1 is Lichun at 315°,
  5 is Qingming) as `solarTerm(term, year)` in `date-chinese` gives it.

      iex> Dayoff.Calendar.Tables.solar_term(:chinese, 2026, 5, 1)
      ~D[2026-04-05]
  """
  @spec solar_term(lunisolar(), integer(), 1..24, integer()) :: Date.t() | nil
  def solar_term(calendar, year, term, day) do
    case lunisolar_year(calendar, year) do
      nil ->
        nil

      %{"solar_terms" => terms} ->
        [gregorian_month, first_day, gregorian_year] = Enum.at(terms, term - 1)
        Date.add(Date.new!(gregorian_year, gregorian_month, first_day), day - 1)
    end
  end

  defp lunisolar_year(calendar, year) do
    years = table(:lunisolar)["calendars"][Atom.to_string(calendar)]

    case years[Integer.to_string(year)] do
      nil ->
        warn_once(calendar, year)
        nil

      entry ->
        entry
    end
  end

  @doc """
  The local calendar date of an equinox or solstice in a timezone, as
  `"MM-DD"`. Fixed offsets (`"+09:00"`) and the named zones the rules use
  are precomputed by the sync.

      iex> Dayoff.Calendar.Tables.equinox(:march, 2026, "+09:00")
      ~D[2026-03-20]

      iex> Dayoff.Calendar.Tables.equinox(:september, 2026, "America/Santiago")
      ~D[2026-09-22]
  """
  @spec equinox(:march | :june | :september | :december, integer(), String.t()) :: Date.t() | nil
  def equinox(season, year, timezone) do
    table = table(:equinox)

    with %{} = entry <- table["years"][Integer.to_string(year)] || warn_once(:equinox, year),
         %{"local" => local} <- entry[Atom.to_string(season)],
         "" <> month_day <-
           local[timezone] ||
             raise(ArgumentError, "no precomputed dates for timezone #{inspect(timezone)}") do
      [month, day] = month_day |> String.split("-") |> Enum.map(&String.to_integer/1)
      Date.new!(year, month, day)
    else
      _ -> nil
    end
  end

  @doc false
  def table(name) do
    key = {__MODULE__, name}

    case :persistent_term.get(key, nil) do
      nil ->
        table = "#{name}.json" |> Data.priv_path() |> File.read!() |> JSON.decode!()
        :persistent_term.put(key, table)
        table

      table ->
        table
    end
  end

  defp warn_once(calendar, year) do
    key = {__MODULE__, :warned, calendar, year}

    unless :persistent_term.get(key, false) do
      :persistent_term.put(key, true)

      Logger.warning(
        "dayoff has no #{calendar} calendar data for #{year}, holidays on that calendar are left out"
      )
    end

    nil
  end
end
